[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
solana_randomness_consumer = "9VkpWFTzgVqw8QPfAFBHWQMh2ZmaGbwZU4uZ8HzM4d9Q"
solana_randomness_service = "RANDMa8hJmXEnKyQtbgrWsg4AgomUG1PFDr1yPP1hFA"

[programs.localnet]
solana_randomness_consumer = "9VkpWFTzgVqw8QPfAFBHWQMh2ZmaGbwZU4uZ8HzM4d9Q"
solana_randomness_service = "RANDMa8hJmXEnKyQtbgrWsg4AgomUG1PFDr1yPP1hFA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# wallet = "~/.config/solana/id.json"
wallet = "~/switchboard_environments_v2/devnet/upgrade_authority/upgrade_authority.json"

[scripts]
close-requests = "tsx ./scripts/close-requests.ts"
initialize = "tsx ./scripts/initialize.ts"
request = "tsx ./scripts/request.ts"
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]]
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]]
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"

[[test.validator.clone]]
address = "AHV7ygefHZQ5extiZ4GbseGANg3AwBWgSUfnUktTrxjd"

[[test.validator.clone]]
address = "2fpdEbugwThMjRQ728Ne4zwGsrjFcCtmYDnwGtzScfnL"
