[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
solana_randomness_consumer = "2z6PF25eaMi2He3v3AqPXvUe467XUpZ2UJbPN6tyHoh5"
solana_randomness_service = "55hPkRP72t4finkHx8KUoHMUDRmS9U9ELig3oRNFt7wY"

[programs.localnet]
solana_randomness_consumer = "2z6PF25eaMi2He3v3AqPXvUe467XUpZ2UJbPN6tyHoh5"
solana_randomness_service = "55hPkRP72t4finkHx8KUoHMUDRmS9U9ELig3oRNFt7wY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/7i.json"

[scripts]
close-requests = "tsx ./scripts/close-requests.ts"
close-state = "tsx ./scripts/close-state.ts"
initialize = "tsx ./scripts/initialize.ts"
request = "tsx ./scripts/request.ts"
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://jarrett-devnet-8fa6.devnet.rpcpool.com/283aba57-34a4-4500-ba4d-1832ff9ca64a"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]]
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]]
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"

[[test.validator.clone]]
address = "AHV7ygefHZQ5extiZ4GbseGANg3AwBWgSUfnUktTrxjd"

[[test.validator.clone]]
address = "2fpdEbugwThMjRQ728Ne4zwGsrjFcCtmYDnwGtzScfnL"
