[package]
name = "solana-randomness-service-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "solana_randomness_service_macros"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
